CREATE TABLE employees(
COMMISSION_PCT	NUMBER(2,2)
,DEPARTMENT_ID	NUMBER(4,0)
,EMAIL	VARCHAR2(25 BYTE)
,EMPLOYEE_ID	NUMBER(6,0)
,FIRST_NAME	VARCHAR2(20 BYTE)
,HIRE_DATE	DATE
,JOB_ID	VARCHAR2(10 BYTE)
,LAST_NAME	VARCHAR2(25 BYTE)
,MANAGER_ID	NUMBER(6,0)
,PHONE_NUMBER VARCHAR2(20 BYTE)
,SALARY	NUMBER(8,2)
);
CREATE TABLE departments(
DEPARTMENT_ID	NUMBER(4,0)
,DEPARTMENT_NAME	VARCHAR2(30 BYTE)
,LOCATION_ID	NUMBER(4,0)
,MANAGER_ID	NUMBER(6,0)
);
CREATE TABLE job_history(
DEPARTMENT_ID	NUMBER(4,0)
,EMPLOYEE_ID	NUMBER(6,0)
,END_DATE	DATE
,JOB_ID	VARCHAR2(10 BYTE)
,START_DATE	DATE
);
CREATE TABLE locations(
CITY	VARCHAR2(30 BYTE)
,COUNTRY_ID	CHAR(2 BYTE)
,LOCATION_ID	NUMBER(4,0)
,POSTAL_CODE	VARCHAR2(12 BYTE)
,STATE_PROVINCE	VARCHAR2(25 BYTE)
,STREET_ADDRESS	VARCHAR2(40 BYTE)
);

CREATE TABLE countries(
COUNTRY_ID CHAR(2 BYTE)
,COUNTRY_NAME VARCHAR2(40 BYTE)
,REGION_ID NUMBER
);
CREATE TABLE regions(
REGION_ID NUMBER
,REGION_NAME VARCHAR2(25)      
);  
CREATE TABLE jobs(
JOB_ID	VARCHAR2(10 BYTE)
,JOB_TITLE	VARCHAR2(35 BYTE)
,MAX_SALARY	NUMBER(6,0)
,MIN_SALARY	NUMBER(6,0)
);

ALTER TABLE countries
    ADD CONSTRAINT COUNTRY_ID_PK PRIMARY KEY(country_id);
ALTER TABLE departments
    ADD CONSTRAINT DEPARTMENT_ID_PK PRIMARY KEY(department_id);
ALTER TABLE employees
    ADD CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(employee_id);
ALTER TABLE job_history
    ADD CONSTRAINT JOBHISTORY_PK PRIMARY KEY(employee_id, start_date);
ALTER TABLE jobs
    ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (job_id);
ALTER TABLE locations 
    ADD CONSTRAINT LOCATION_ID_PK PRIMARY KEY(location_id);
ALTER TABLE regions
    ADD CONSTRAINT REGION_ID_PK PRIMARY KEY(region_id);
    

ALTER TABLE departments
    ADD CONSTRAINT DEPARTMENTS_manager_id_FK FOREIGN KEY(MANAGER_ID)
        REFERENCES employees(employee_id);
ALTER TABLE departments
    ADD CONSTRAINT DEPARTMENTS_location_id_FK FOREIGN KEY(location_id)
        REFERENCES locations(location_id);
        
ALTER TABLE employees
    ADD CONSTRAINT EMPLOYEES_job_id_FK FOREIGN KEY(job_id)
        REFERENCES jobs(job_id);
ALTER TABLE employees
    ADD CONSTRAINT EMPLOYEES_manager_id_FK FOREIGN KEY(manager_id)
        REFERENCES employees(employee_id);
ALTER TABLE employees
    ADD CONSTRAINT EMPLOYEES_department_id_FK FOREIGN KEY(department_id)
        REFERENCES departments(department_id);
        
ALTER TABLE job_history
    ADD CONSTRAINT JOB_HISTORY_job_id_FK FOREIGN KEY(job_id)
        REFERENCES jobs(job_id);
ALTER TABLE job_history
    ADD CONSTRAINT JOB_HISTORY_department_id_FK FOREIGN KEY(department_id)
        REFERENCES departments(department_id);
ALTER TABLE job_history
    ADD CONSTRAINT JOB_HISTORY_employee_id_FK FOREIGN KEY(employee_id)
        REFERENCES employees(employee_id);
        
ALTER TABLE locations
    ADD CONSTRAINT LOCATIONS_country_id_FK FOREIGN KEY(country_id)
        REFERENCES countries(country_id);
ALTER TABLE countries
    ADD CONSTRAINT COUNTRIES_region_id_FK FOREIGN KEY(region_id)
        REFERENCES regions(region_id);        


  
--»Æ¿Â¿⁄.sql